apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web-backendconfig
  namespace: app
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /login/
    port: 8000
